Repository infrahq/infra, pull requests merged in 2022-04, with the labels that each got.

#1596 maintain(main): release 0.10.3
  .release-please-manifest.json
  CHANGELOG.md
  docs/api/openapi3.json
  docs/install/upgrading.md
  helm/charts/infra/Chart.yaml
  internal/version.go
Labels: autorelease/pending

#1611 api: more robust structure for building routes
  internal/server/routes.go
  internal/server/server.go
  internal/server/server_test.go
Labels: area/api

#1713 fix: grant input dropdown reset after sharing with a user
  ui/components/grant.js
  ui/components/input.js
Labels: kind/bug, area/ui

#1721 fix: user list is sorted on create and update
  ui/components/grant.js
  ui/pages/destinations/index.js
Labels: kind/bug, area/ui

#1714 fix: hide `revoke` button for self in settings > admins
  ui/pages/settings/admin.js
Labels: kind/bug, area/ui

#1706 maintain(main): release 0.11.1
  .release-please-manifest.json
  CHANGELOG.md
  docs/api/openapi3.json
  docs/install/upgrading.md
  helm/charts/infra/Chart.yaml
  internal/version.go
Labels: autorelease/pending

#1749 maintain(main): release 0.12.0
  .release-please-manifest.json
  CHANGELOG.md
  docs/api/openapi3.json
  docs/install/upgrading.md
  helm/charts/infra/Chart.yaml
  internal/version.go
Labels: autorelease/pending

#1747 fix: cluster add page ui bugs
  ui/components/input.js
  ui/components/modals/fullscreen.js
  ui/pages/destinations/add.js
  ui/tailwind.config.js
Labels: kind/bug, area/ui

#1758 maintain(main): release 0.12.1
  .release-please-manifest.json
  CHANGELOG.md
  docs/api/openapi3.json
  docs/install/upgrading.md
  helm/charts/infra/Chart.yaml
  internal/version.go
Labels: autorelease/pending

#1790 maintain(main): release 0.12.2
  .release-please-manifest.json
  CHANGELOG.md
  docs/api/openapi3.json
  docs/install/upgrading.md
  helm/charts/infra/Chart.yaml
  internal/version.go
Labels: autorelease/pending
