Repository infrahq/infra, pull requests merged in 2022-05, with the labels that each got.

#1805 improve(docs): First draft of the API development guidelines
  docs/api/guidelines.md
Labels: area/documentation

#1785 fix: general ui bugs
  ui/components/empty-table.js
  ui/components/grant.js
  ui/components/input.js
  ui/components/layouts/dashboard.js
  ui/components/modals/delete.js
  ui/components/modals/fullscreen.js
  ui/components/modals/info.js
  ui/components/table.js
  ui/pages/destinations/add.js
  ui/pages/destinations/index.js
  ui/pages/login/finish.js
  ui/pages/login/index.js
  ui/pages/providers/add/details.js
  ui/pages/providers/add/index.js
  ui/pages/providers/index.js
  ui/pages/settings/admin.js
  ui/pages/settings/index.js
  ui/pages/signup/index.js
  ui/styles/globals.css
  ui/tailwind.config.js
Labels: kind/bug, area/ui

#1832 maintain(main): release 0.13.0
  .release-please-manifest.json
  CHANGELOG.md
  docs/api/openapi3.json
  docs/install/upgrading.md
  helm/charts/infra/Chart.yaml
  internal/version.go
Labels: autorelease/pending

#1973 ci: add daily schedule job to run fuzzing
  .github/labels.yaml
  .github/workflows/fuzz.yaml
Labels: action/fuzz

#1955 maintain(main): release 0.13.1
  .release-please-manifest.json
  CHANGELOG.md
  Dockerfile
  docs/api/openapi3.json
  docs/install/upgrading.md
  helm/charts/infra/Chart.yaml
  internal/version.go
Labels: autorelease/pending

#2045 improve: modified notfoundhandler to check accept header
  api/client.go
  internal/server/routes.go
  internal/server/server_test.go
Labels: area/api

#2152 Adding community links for discussion
  README.md
Labels: area/documentation
