Repository infrahq/infra, pull requests merged in 2023-01, with the labels that each got.

#3957 Fix CI failure in acceptance tests
  .github/workflows/ci-core.yaml
Labels: action/test-acceptance

#3928 add selinux module for infra
  .github/workflows/cd-binaries.yaml
  .github/workflows/ci-core.yaml
  .goreleaser.yml
  package-files/postinstall.sh
  package-files/selinux/infra.te
Labels: action/test-acceptance

#3962 Add debian and redhat destination to SSH acceptance tests
  .goreleaser.yml
  test/docker-compose.yaml
  test/dockerfiles/Dockerfile.debian
  test/dockerfiles/Dockerfile.redhat
  test/dockerfiles/install-debian.sh
  test/dockerfiles/install-redhat.sh
  test/dockerfiles/server.yaml
  test/setup.sh
  test/ssh_test.go
Labels: area/destinations/ssh, action/test-acceptance

#3925 Improve error output from infra ssh
  internal/cmd/ssh.go
  internal/cmd/ssh_test.go
Labels: area/destinations/ssh, action/test-acceptance

#3949 Remove old client config migrations
  internal/cmd/config.go
  internal/cmd/config_migration.go
Labels: kind/maintenance

#3967 Update acceptance test to use the same instructions as the docs
  .github/workflows/ci-core.yaml
  test/dockerfiles/install-debian.sh
  test/dockerfiles/install-redhat.sh
Labels: action/test-acceptance

#3950 Inline and reduce database encryption at-rest logic
  internal/cmd/server.go
  internal/cmd/server_test.go
  internal/server/data/data.go
  internal/server/data/encrypt/keys.go
  internal/server/data/encrypt/seal.go
  internal/server/data/encrypt/seal_test.go
  internal/server/data/encryption_key.go
  internal/server/models/encryption.go
  internal/server/models/encryption_test.go
  internal/server/server.go
  internal/server/server_test.go
  internal/testing/patch/patch.go
Labels: kind/maintenance

#3964 Add a default expiration time to all user public keys
  api/user.go
  docs/api/openapi3.json
  internal/cmd/ssh.go
  internal/server/data/identity_test.go
  internal/server/data/migrations.go
  internal/server/data/migrations_test.go
  internal/server/data/schema.sql
  internal/server/data/user_public_keys.go
  internal/server/data/user_public_keys_test.go
  internal/server/models/identity.go
  internal/server/server.go
  internal/server/users.go
  internal/server/users_test.go
Labels: area/destinations/ssh, action/test-acceptance

#3930 Reduce server config to only bootstrapping of user and credentials
  internal/cmd/connector_test.go
  internal/cmd/helpers_test.go
  internal/cmd/kubernetes_test.go
  internal/cmd/list_test.go
  internal/cmd/login_test.go
  internal/cmd/server_test.go
  internal/cmd/ssh_test.go
  internal/cmd/sshauthkeys_test.go
  internal/cmd/users_test.go
  internal/server/config.go
  internal/server/config_test.go
  internal/server/data/grant.go
  internal/server/data/grant_test.go
  internal/server/data/identity.go
  internal/server/data/identity_test.go
  internal/server/data/provider.go
  internal/server/data/provider_test.go
  internal/server/helpers_test.go
  internal/server/options_migrations.go
  internal/server/server.go
  internal/server/server_test.go
  test/dockerfiles/server.yaml
  test/go.mod
  test/go.sum
Labels: action/test-acceptance

#3951 Reduce secret loading of secrets to only config files and environment variables
  go.mod
  go.sum
  internal/cmd/login_test.go
  internal/cmd/server_test.go
  internal/server/config.go
  internal/server/config_test.go
  internal/server/server.go
  internal/server/server_test.go
  internal/server/tls.go
  internal/server/tls_test.go
Labels: kind/maintenance

#4010 Fix configs that used file: prefix
  dev/server.yaml
  test/docker-compose.yaml
Labels: action/test-acceptance

#4011 Replace grants.subject with grants.subject_id and grants.subject_kind
  internal/access/access.go
  internal/access/access_key_test.go
  internal/access/access_test.go
  internal/access/grant.go
  internal/access/identity_test.go
  internal/cmd/helpers_test.go
  internal/server/access_keys_test.go
  internal/server/config.go
  internal/server/data/destination_test.go
  internal/server/data/grant.go
  internal/server/data/grant_test.go
  internal/server/data/group.go
  internal/server/data/group_test.go
  internal/server/data/identity.go
  internal/server/data/identity_test.go
  internal/server/data/migrations.go
  internal/server/data/migrations_test.go
  internal/server/data/organization.go
  internal/server/data/organization_test.go
  internal/server/data/schema.sql
  internal/server/debug_test.go
  internal/server/destination_test.go
  internal/server/grants.go
  internal/server/grants_test.go
  internal/server/helpers_test.go
  internal/server/middleware_test.go
  internal/server/models/grant.go
  internal/server/models/group.go
  internal/server/models/identity.go
  internal/server/organizations_test.go
  internal/server/signup.go
  internal/server/signup_test.go
  internal/server/users_test.go
  uid/polymorphic.go
  uid/polymorphic_test.go
Labels: kind/maintenance, action/test-acceptance

#4027 Reduce the use of gin.Context - part 1
  internal/cmd/ssh.go
  internal/server/handlers.go
  internal/server/providers.go
  internal/server/routes.go
  internal/server/signup.go
Labels: kind/maintenance

#4029 Remove use of `gin` in the connector
  internal/connector/connector.go
  internal/connector/proxy.go
  metrics/metrics.go
Labels: kind/maintenance

#4028 Remove `gin.Context` from `access` package
  internal/access/access.go
  internal/access/access_key.go
  internal/access/access_key_test.go
  internal/access/access_test.go
  internal/access/credential.go
  internal/access/credential_test.go
  internal/access/destination.go
  internal/access/grant.go
  internal/access/group.go
  internal/access/identity.go
  internal/access/identity_test.go
  internal/access/organization.go
  internal/access/passwordreset.go
  internal/access/provider.go
  internal/access/scim.go
  internal/access/settings.go
  internal/server/access_keys.go
  internal/server/debug.go
  internal/server/destinations.go
  internal/server/grants.go
  internal/server/groups.go
  internal/server/handlers.go
  internal/server/logging.go
  internal/server/organizations.go
  internal/server/passwordreset.go
  internal/server/providers.go
  internal/server/routes.go
  internal/server/scim.go
  internal/server/settings.go
  internal/server/signup.go
  internal/server/telemetry.go
  internal/server/users.go
Labels: kind/maintenance

#4050 Fix HTTP metric in connector proxy
  internal/connector/proxy.go
Labels: kind/bug

#4053 Fix panic in infra ssh command
  internal/cmd/ssh.go
  internal/cmd/ssh_keys.go
  internal/cmd/ssh_test.go
Labels: kind/bug, area/destinations/ssh, action/test-acceptance

#4030 Reduce the use of `gin.Context` in `server` package
  internal/access/request.go
  internal/server/debug.go
  internal/server/deviceflow.go
  internal/server/errors.go
  internal/server/errors_test.go
  internal/server/handlers.go
  internal/server/logging.go
  internal/server/logging_test.go
  internal/server/routes.go
  internal/server/signup.go
Labels: kind/maintenance

#4090 Call validate in versioned handlers
  docs/dev/api-versioned-handlers.md
  internal/server/access_keys.go
  internal/server/signup.go
Labels: kind/bug, area/api
